<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsTestProject>true</IsTestProject><IsPackable>false</IsPackable></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\DatabaseXmlManager.Core\DatabaseXmlManager.Core.csproj" />
    <ProjectReference Include="..\..\src\DatabaseXmlManager.Xml\DatabaseXmlManager.Xml.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.TestFramework" />
  </ItemGroup>
</Project>
